"use client";

interface MemoBoxProps {
  memo: string;
}

export default function MemoBox({ memo }: MemoBoxProps) {
  return (
    <section className="border border-[#0f1a10] bg-[#0a1210] p-5">
      <h2 className="mb-5 text-[10px] uppercase tracking-[0.2em] text-[#2e4d30]">
        AI STRATEGY MEMO
      </h2>
      {memo ? (
        <p className="whitespace-pre-line text-sm leading-[1.85] text-[#c8e8c0]">
          {memo}
        </p>
      ) : (
        <div className="grid gap-3">
          <div className="h-4 w-5/6 animate-pulse bg-[#111c12]" />
          <div className="h-4 w-full animate-pulse bg-[#111c12]" />
          <div className="h-4 w-2/3 animate-pulse bg-[#111c12]" />
          <p className="mt-2 text-xs text-[#2e4d30]">Writing strategy...</p>
        </div>
      )}
      <p className="mt-6 text-[10px] leading-5 text-[#2e4d30]">
        Generated by Gemini · Scores derived from RBI, TRAI, NCCD public data ·
        For illustrative purposes
      </p>
    </section>
  );
}
